import dotenv from "dotenv";
import { writeFile } from "node:fs/promises";

dotenv.config({ path: ".env.local", quiet: true });

// Rebuilds src/lib/catalogue-nouns.ts from the catalogue's own category names,
// so product recognition covers the whole catalogue instead of a hand-typed
// word list. Re-run after a catalogue import: pnpm catalogue:nouns

// Head nouns that are also everyday chat or attribute words. Treating them as
// product requests would send "I need help", "all set" or "cast iron" to search.
const excluded = new Set([
  "need", "care", "service", "set", "setup", "supply", "system", "unit", "item", "piece", "room", "trendy",
  "essential", "component", "food", "hot", "bar", "mary", "agent", "amenity", "lobby", "organization",
  "receiving", "housekeeping", "merchandising", "refrigeration", "seating", "station", "platform", "washing",
  "warming", "wear", "gear", "edible", "electrical", "decorating", "cutting", "carving", "paring", "larding",
  "deep-fry", "q-post", "rest", "roll", "string", "frame", "handle", "guard", "ring", "screen", "card", "floor",
  "wheel", "weight", "iron", "steel", "stone", "wax", "spare", "sweep", "drink", "range", "press", "pick", "case",
  "base", "net", "pin", "knive", "eqiupment", "refridgerator", "shelve",
  // What the customer cooks or serves, not equipment: "for soup" answers a
  // stockpot question. Real requests ("wine glass", "pizza pan") are covered by
  // the hand-written product words.
  "egg", "ice", "soup", "oil", "bread", "cake", "vegetable", "sugar", "salt", "sauce", "cream", "jelly", "pasta",
  "pizza", "sausage", "lobster", "snail", "waffle", "soda", "wine", "champagne", "cocktail", "beer", "tea", "coffee",
  "grill", "chef", "butcher",
  // Words customers also use about the website, their business or small talk.
  "server", "display", "scale", "carrier", "truck", "table", "board", "stand", "menu", "holder", "saw", "susan",
]);

const singular = (word: string) => word
  .replace(/ies$/, "y")
  .replace(/(ches|shes|sses|xes)$/, (ending) => ending.slice(0, -2))
  .replace(/(?<!s)s$/, "");

async function main() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY;
  if (!url || !key) throw new Error("SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY are required");
  const names = new Set<string>();
  for (let from = 0; ; from += 1000) {
    const response = await fetch(`${url}/rest/v1/products?select=subcategory,third_category&status=in.(Active,New)`, {
      headers: { apikey: key, authorization: `Bearer ${key}`, Range: `${from}-${from + 999}` },
    });
    if (!response.ok) throw new Error(`SUPABASE_${response.status}`);
    const rows = await response.json() as Array<{ subcategory: string | null; third_category: string | null }>;
    for (const row of rows) for (const name of [row.subcategory, row.third_category]) if (name) names.add(name);
    if (rows.length < 1000) break;
  }
  const nouns = new Set<string>();
  for (const name of names) {
    for (const part of name.split(/,|\band\b|&|\//i)) {
      const head = part.split(/\b(?:for|to|with)\b/i)[0].trim().toLowerCase().split(/\s+/).at(-1);
      if (!head || !/^[a-z-]{3,}$/.test(head)) continue;
      const noun = singular(head);
      if (!excluded.has(noun)) nouns.add(noun);
    }
  }
  const sorted = [...nouns].sort();
  const body = `// Generated by scripts/generate-catalogue-nouns.ts from the catalogue's category names. Do not edit by hand.\nexport const catalogueNouns: ReadonlySet<string> = new Set(${JSON.stringify(sorted)});\n`;
  await writeFile("src/lib/catalogue-nouns.ts", body, "utf8");
  console.log(`Wrote ${sorted.length} catalogue nouns from ${names.size} category names.`);
}

main().catch((error) => { console.error(error); process.exitCode = 1; });
