import dotenv from "dotenv";
import { writeFile } from "node:fs/promises";

dotenv.config({ path: ".env.local", quiet: true });

// Rebuilds src/lib/catalogue-ranges.ts from the catalogue's category names: each top-level range, its sections and their types.
// Claire reads the list in her prompt, so she knows what the store carries (owner, 2 Oct: she said we don't carry furniture).
// Re-run after every catalogue import, with catalogue:nouns: pnpm catalogue:ranges

const named = (name: string | null) => {
  const trimmed = (name ?? "").trim();
  return trimmed && trimmed !== "-" ? trimmed : null;
};
const sorted = (names: Iterable<string>) => [...names].sort((a, b) => a.localeCompare(b, "en"));

async function main() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY;
  if (!url || !key) throw new Error("SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY are required");
  const tree = new Map<string, Map<string, Set<string>>>();
  for (let from = 0; ; from += 1000) {
    const response = await fetch(`${url}/rest/v1/products?select=category,subcategory,third_category&status=in.(Active,New)`, {
      headers: { apikey: key, authorization: `Bearer ${key}`, Range: `${from}-${from + 999}` },
    });
    if (!response.ok) throw new Error(`SUPABASE_${response.status}`);
    const rows = await response.json() as Array<{ category: string | null; subcategory: string | null; third_category: string | null }>;
    for (const row of rows) {
      const range = named(row.category);
      const section = named(row.subcategory);
      if (!range || !section) continue; // a range with no named section is left out (Books & Guides)
      if (!tree.has(range)) tree.set(range, new Map());
      const sections = tree.get(range)!;
      if (!sections.has(section)) sections.set(section, new Set());
      const type = named(row.third_category);
      if (type && type !== section) sections.get(section)!.add(type); // a type named as its section adds nothing
    }
    if (rows.length < 1000) break;
  }
  const ranges = sorted(tree.keys()).map((range) => {
    const sections = tree.get(range)!;
    return [range, sorted(sections.keys()).map((section) => [section, sorted(sections.get(section)!)] as const)] as const;
  });
  const sectionCount = ranges.reduce((sum, [, sections]) => sum + sections.length, 0);
  const typeCount = ranges.reduce((sum, [, sections]) => sum + sections.reduce((count, [, types]) => count + types.length, 0), 0);
  // One section per line, so an import's changes show line by line in a diff.
  const lines = ranges.map(([range, sections]) => `  [${JSON.stringify(range)}, [\n${sections.map((section) => `    ${JSON.stringify(section)},\n`).join("")}  ]],\n`);
  const body = "// Generated by scripts/generate-catalogue-ranges.ts from the catalogue's category names. Do not edit by hand.\n"
    + "export const catalogueRanges: ReadonlyArray<readonly [range: string, sections: ReadonlyArray<readonly [section: string, types: readonly string[]]>]> = [\n"
    + `${lines.join("")}];\n`;
  await writeFile("src/lib/catalogue-ranges.ts", body, "utf8");
  console.log(`${ranges.length} ranges, ${sectionCount} sections, ${typeCount} types`);
}

main().catch((error) => { console.error(error); process.exitCode = 1; });
